version: '3'
services:

  flask:
    build:
      context: app
      dockerfile: Dockerfile
    container_name: flask
    image: digitalocean.com/flask-python:3.6
    restart: unless-stopped
    environment:
      APP_ENV: "prod"
      APP_DEBUG: "False"
      APP_PORT: 5000
      MONGODB_DATABASE: gamedb
      MONGODB_USERNAME: flaskuser
      MONGODB_PASSWORD: super_secret_password
      MONGODB_HOSTNAME: mongodb
    volumes:
      - .:/var/www
    ports:
      - 5000:5000
    depends_on:
      - mongodb

  mongodb:
    image: mongo:4.0.8
    container_name: mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: gamedb
      MONGODB_DATA_DIR: /data/db
      MONDODB_LOG_DIR: /dev/null
    ports:
      - 27017:27017
    volumes:
      - mongodbdata:/data/db
    
  nginx:
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - flask

volumes:
  mongodbdata:
    driver: local
